# Generated by Django 3.1.1 on 2020-10-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matches',
            table='matches',
        ),
    ]
